import { ExplanationCard } from './ExplanationCard';
import { ApprovalCard } from './ApprovalCard';
import { Card, CardHeader, CardTitle, CardMeta } from '../../components/ui/Card';
import { Badge } from '../../components/ui/Badge';
import { useExplainability } from '../../hooks/useExplainability';
import type { ExplanationStep, Constraint } from '../../lib/types';

const CONSTRAINTS: Constraint[] = [
  { id: 'c1', label: 'Budget limit', value: '€8,500 total', type: 'hard' },
  { id: 'c2', label: 'Max layover', value: '2 hours', type: 'hard' },
  { id: 'c3', label: 'Hotel check-in', value: 'After 14:00', type: 'hard' },
  { id: 'c4', label: 'Preferred airlines', value: 'BA, Lufthansa', type: 'soft' },
  { id: 'c5', label: 'Preferred hotel tier', value: '4–5 star', type: 'soft' },
  { id: 'c6', label: 'Activity density', value: 'Max 2 per half-day', type: 'soft' },
  { id: 'c7', label: 'Meal preference', value: 'Local cuisine', type: 'soft' },
  { id: 'c8', label: 'Airport buffer', value: 'Min 2h before departure', type: 'hard' },
];

const STEPS: ExplanationStep[] = [
  {
    id: 'step1',
    title: 'Itinerary parsing and activity graph construction',
    description: 'The optimizer loaded 31 activities and built a directed acyclic graph representing temporal dependencies: transport legs, hotel check-in/out windows, and activity start times. This graph enables the CP-SAT solver to reason about schedule feasibility without brute-force enumeration.',
    stepType: 'analysis',
  },
  {
    id: 'step2',
    title: 'Hard constraint verification',
    description: 'All 8 hard constraints were checked against the current itinerary. Constraint C-03 (Hotel check-in after 14:00 in Florence) was violated: the 14:30 Rome–Florence train arrives at 17:15 but hotel check-in closes the luggage storage at 17:00, creating a 15-minute conflict under traffic assumptions. This triggered the schedule optimization pass.',
    stepType: 'constraint_check',
  },
  {
    id: 'step3',
    title: 'Cost and comfort scoring',
    description: 'A weighted multi-objective score was computed: 40% cost efficiency, 35% schedule efficiency, 25% comfort. The current itinerary scored 0.847. The optimizer searched for Pareto-improving changes — modifications that improve at least one objective without degrading others. The 11:00 train improves both cost (−€48) and schedule efficiency, achieving a score of 0.887.',
    stepType: 'scoring',
  },
  {
    id: 'step4',
    title: 'Candidate selection and conflict resolution',
    description: 'From 847 candidate modifications generated by the CP-SAT branching, 3 non-conflicting changes were selected using a greedy top-k approach ranked by expected improvement / confidence ratio. The hotel upgrade was included despite the cost increase because the comfort improvement (72 → 89) and availability risk offset the budget impact within the remaining slack (€3,160).',
    stepType: 'selection',
  },
  {
    id: 'step5',
    title: 'Validation against all constraints',
    description: 'The proposed itinerary was re-validated against all 8 hard constraints. All pass. Soft constraints: 11 of 12 satisfied; C-soft-7 (local cuisine preference for dinner) was relaxed on Aug 16 due to restaurant availability, replaced with a comparable rated alternative.',
    stepType: 'validation',
  },
];

interface ExplainabilityPanelProps {
  onApprove: () => void;
  onRequestChanges: (comment: string) => void;
}

export function ExplainabilityPanel({ onApprove, onRequestChanges }: ExplainabilityPanelProps) {
  // Use a mock itinerary ID for the demo since we don't pass it in props
  const itineraryId = 'mock-itinerary-id';
  const { data: explanations, isLoading } = useExplainability(itineraryId);

  const confidence = explanations && explanations.length > 0 
    ? Math.round(explanations.reduce((sum, e) => sum + e.confidence, 0) / explanations.length * 100)
    : 94;

  const dynamicExplanation = explanations && explanations.length > 0
    ? `The AI analyzed the itinerary and identified ${explanations.length} optimizations. ` + explanations.map(e => e.human_explanation).join(' ')
    : 'The AI analyzed the itinerary and applied optimizations to improve cost, schedule, and comfort.';

  const dynamicSteps: ExplanationStep[] = explanations
    ? explanations.map((e, index) => ({
        id: e.id,
        title: `Optimization: ${e.activity_changed}`,
        description: `Reason: ${e.reason}. ${e.human_explanation}`,
        stepType: index % 2 === 0 ? 'analysis' : 'scoring',
      }))
    : STEPS;

  if (isLoading) return <div className="p-8 text-center">Loading explanations...</div>;

  return (
    <div className="max-w-3xl mx-auto space-y-8">

      <div>
        <div className="flex items-center gap-3 mb-1">
          <h1 className="text-2xl font-bold" style={{ fontFamily: 'var(--font-display)' }}>
            AI Explanation
          </h1>
          <Badge variant="ai">AI-generated</Badge>
        </div>
        <p className="text-sm" style={{ color: 'var(--muted-foreground)' }}>
          Italy Family Trip · Optimization opt-8f3a9c · {explanations?.length ?? 3} changes proposed
        </p>
      </div>

      {/* Natural language explanation */}
      <Card ai padding="md">
        <CardHeader>
          <div>
            <CardTitle>What the AI did and why</CardTitle>
            <CardMeta className="mt-0.5">Plain English summary of optimization decisions</CardMeta>
          </div>
        </CardHeader>
        <p className="text-sm leading-relaxed">{dynamicExplanation}</p>
      </Card>

      {/* Confidence */}
      <Card padding="md">
        <CardHeader>
          <CardTitle>Confidence</CardTitle>
          <span
            className="text-sm font-bold"
            style={{ color: confidence >= 80 ? 'var(--success)' : confidence >= 60 ? 'var(--warning)' : 'var(--error)', fontFamily: 'var(--font-mono)' }}
          >
            {confidence}%
          </span>
        </CardHeader>
        <div>
          <div className="h-2 rounded-full overflow-hidden mb-2" style={{ backgroundColor: 'var(--muted)' }}>
            <div
              className="h-full rounded-full transition-all duration-700"
              style={{
                width: `${confidence}%`,
                backgroundColor: confidence >= 80 ? 'var(--success)' : confidence >= 60 ? 'var(--warning)' : 'var(--error)',
              }}
            />
          </div>
          <p className="text-xs" style={{ color: 'var(--muted-foreground)' }}>
            High confidence based on 8,941 iterations of the CP-SAT solver, 3 independent constraint validation passes, and historical outcome data from 1,200+ similar itineraries.
          </p>
        </div>
      </Card>

      {/* Constraints */}
      <Card padding="md">
        <CardHeader>
          <CardTitle>Constraints considered</CardTitle>
          <div className="flex gap-2">
            <Badge variant="failed">
              {CONSTRAINTS.filter(c => c.type === 'hard').length} hard
            </Badge>
            <Badge variant="pending">
              {CONSTRAINTS.filter(c => c.type === 'soft').length} soft
            </Badge>
          </div>
        </CardHeader>
        <div className="flex flex-wrap gap-2">
          {CONSTRAINTS.map(c => (
            <span
              key={c.id}
              className="text-xs px-2.5 py-1.5 rounded-full"
              style={{
                border: `1px solid ${c.type === 'hard' ? 'color-mix(in srgb, var(--error) 30%, var(--border))' : 'var(--border)'}`,
                backgroundColor: c.type === 'hard' ? 'color-mix(in srgb, var(--error) 5%, var(--card))' : 'var(--muted)',
                color: c.type === 'hard' ? 'var(--foreground)' : 'var(--muted-foreground)',
              }}
            >
              <span className="font-medium">{c.label}:</span> {c.value}
            </span>
          ))}
        </div>
      </Card>

      {/* Reasoning steps */}
      <div>
        <h2 className="text-sm font-semibold mb-3" style={{ fontFamily: 'var(--font-display)' }}>
          Reasoning steps
        </h2>
        <div className="space-y-2">
          {dynamicSteps.map((step, i) => (
            <ExplanationCard key={step.id} step={step} index={i} />
          ))}
        </div>
      </div>

      {/* Approval */}
      <ApprovalCard
        optimizationId="opt-8f3a9c"
        onApprove={onApprove}
        onRequestChanges={onRequestChanges}
      />
    </div>
  );
}
